### ISSUE TITLE
[FR] Local File System sync

### ISSUE THREAD

**Issue by jnslr** [0xGG/crossnote-app#119]
First of all: **Thanks for the great work!!**

Would be great being able to **edit local files**.
E.g. **open folder** function that lists all the *\*.md* files and the folder structure and allows editing of those files locally. (Similar to VsCode open folder function).

Maybe native file system api ([see here ](https://github.com/WICG/native-file-system/blob/master/EXPLAINER.md) or [here](https://wicg.github.io/native-file-system/)) could be used.

**Comment by shd101wyy** [comment]
Hi @Ux1F595 , thank you very much for your suggestions. Yes I also looked into the native file system APIs. But it seems that the API is still in draft phase and not ready for all browsers. If I remember correctly, it’s now an experimental feature of chrome. But of course I will slowly push it forward. Thank you!

**Comment by aisbergde** [comment]
can you please explain in the documentation the technical background how this app currently works? I would like to investigate if it is possible to use crossnote together with an existing plain text based notes system. 

I had a look on the welcome-notebook repository and it looks like it could be compatible:
- Each note is a markdown file
- each note has a yaml front matter

the issue with the yaml is the extra "note", but I could imagine an option to avoid this "note" to make it compatible to some other systems storing their metadata in yaml. Without this "note:" it would be nearly perfect. 

```yaml
---
note:
    createdAt: 2020-03-28T07:52:59.238Z
    modifiedAt: 2020-03-28T08:37:27.812Z
    tags: [tutorial]
    id: ""
---
```

because it is a git repository it can be cloned on desktop and on android. 

In my understanding I could use any other app to add, update and delete content. On Desktop VSC, on Android some other apps. 

But this would work only if crossnote uses the same clone. And reading this issue here I am not sure how crossnote works:

does it clone the repository on disk where I can access it using any editor or is the clone stored in a hidden place which cannot be accessed? In this case I have no idea how I could use other programs to change the content. The only idea would be to have a second clone.

But maybe crossnote can not only connect to a github repository but directly to a local repository?

So maybe for the desktop there could be some solutions. But on Android? I should be able to use my favorite markdown editor on android. Currently it looks like there is only the build in editor, which is limited.

**Comment by shd101wyy** [comment]
Hi @aisbergde , the web version of crossnote uses [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git) to download arbitrary git repositories and store them in browser storage [lightning-fs](https://github.com/isomorphic-git/lightning-fs) backed by indexeddb. Crossnote doesn't have capability to access local files on your system now. As the native file system API gets mature, we might support opening local directories on your computer in the future. Thanks

**Comment by aisbergde** [comment]
Thank you for explaining. I will try to use with a local git repository as origin. In this case it will double the content, but I should be able to synchronize content between crossnote and another local repository where I could use my favorite editors.

If it uses a git client maybe in the future the feature to adding an additional remote could be implemented. Then github could be the main repository but an additional local remote could be just added. 

The main idea to use git and markdown is great. Regarding the build in editor I need to think about how to use my favorite editors.

**Comment by shd101wyy** [comment]
Hi @Ux1F595 , opening local directory is now supported in V3: https://0xgg.io/crossnote 
Thank you :)
